/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.PrincipalController;

/**
 *
 * @author sebas
 */
public class GUICreditos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUICreditos.class.getName());

    /**
     * Creates new form GUICreditos
     */
    public GUICreditos(PrincipalController controlador) {
        initComponents();
        escuchar(controlador);
    }

    
    public void escuchar(PrincipalController controlador){
        btnAtrasCreditos.addActionListener(controlador);     
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtrasCreditos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlFondoCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtrasCreditos.setActionCommand("atrasCreditos");
        btnAtrasCreditos.setBorderPainted(false);
        btnAtrasCreditos.setContentAreaFilled(false);
        getContentPane().add(btnAtrasCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Diseñado por: Yuliana Masis");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Desarrollado por: Sebastian Vasquez");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 50));

        jlFondoCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroCreditos.png"))); // NOI18N
        getContentPane().add(jlFondoCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 860, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlFondoCreditos;
    // End of variables declaration//GEN-END:variables
}
