/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.PrincipalController;

/**
 *
 * @author sebas
 */
public class GUIHistoriaJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIHistoriaJuego.class.getName());

    /**
     * Creates new form GUIHistoriaJuego
     */
    public GUIHistoriaJuego(PrincipalController controlador) {
        initComponents();
        escuchar(controlador);
    }

    
    public void escuchar(PrincipalController controlador){
        btnHistoriaJuego.addActionListener(controlador);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jlHistoriaJuegoTitulo = new javax.swing.JLabel();
        btnHistoriaJuego = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlHistoriaJuegoTitulo1 = new javax.swing.JLabel();
        jlHistoriaJuegoTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("2 equipos de polos opuestos compiten \npor ver cual de los 2 se queda primero \nsin puntos o cual de los 2 llega primero \na la meta para de  esta forma ganar \nel juego.");
        jTextArea2.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 490, 270));

        jlHistoriaJuegoTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlHistoriaJuegoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHistoriaJuegoTitulo.setToolTipText("");
        jlHistoriaJuegoTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlHistoriaJuegoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 80));

        btnHistoriaJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnHistoriaJuego.setToolTipText("");
        btnHistoriaJuego.setActionCommand("atrasHistoriaJuego");
        btnHistoriaJuego.setBorderPainted(false);
        btnHistoriaJuego.setContentAreaFilled(false);
        btnHistoriaJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoriaJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroHistoria.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jlHistoriaJuegoTitulo1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlHistoriaJuegoTitulo1.setText("2 equipos de polos opuestos compiten por ver cual de los 2 se queda");
        getContentPane().add(jlHistoriaJuegoTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 20));

        jlHistoriaJuegoTitulo2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlHistoriaJuegoTitulo2.setText("2 equipos de polos opuestos compiten por ver cual de los 2 se queda");
        getContentPane().add(jlHistoriaJuegoTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoriaJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoriaJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoriaJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel jlHistoriaJuegoTitulo;
    private javax.swing.JLabel jlHistoriaJuegoTitulo1;
    private javax.swing.JLabel jlHistoriaJuegoTitulo2;
    // End of variables declaration//GEN-END:variables
}
