/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.PrincipalController;

/**
 *
 * @author sebas
 */
public class GUIInstrucciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInstrucciones.class.getName());

    /**
     * Creates new form GUIInstrucciones
     */
    public GUIInstrucciones(PrincipalController controlador) {
        initComponents();
        escuchar(controlador);
    }

    
    public void escuchar(PrincipalController controlador){
        btnAtrasInstrucciones.addActionListener(controlador);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlInstruccionesTitulo = new javax.swing.JLabel();
        btnAtrasInstrucciones = new javax.swing.JButton();
        jlInstruccionesFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlInstruccionesTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jlInstruccionesTitulo.setText("Instrucciones");
        getContentPane().add(jlInstruccionesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        btnAtrasInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtrasInstrucciones.setActionCommand("atrasInstrucciones");
        btnAtrasInstrucciones.setBorderPainted(false);
        btnAtrasInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnAtrasInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, -1));

        jlInstruccionesFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroInstrucciones.png"))); // NOI18N
        getContentPane().add(jlInstruccionesFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasInstrucciones;
    private javax.swing.JLabel jlInstruccionesFondo;
    private javax.swing.JLabel jlInstruccionesTitulo;
    // End of variables declaration//GEN-END:variables
}
