/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.PrincipalController;

/**
 *
 * @author sebas
 */
public class GUIJugador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIJugador.class.getName());

    /**
     * Creates new form GUIJugador
     */
    public GUIJugador(PrincipalController controlador) {
        initComponents();
        btnContinuar.addActionListener(controlador);
    }

    public String getCbColor() {
        return (String) cbColor.getSelectedItem();
    }

    public String getTxtJugador1() {
        return txtJugador1.getText();
    }

    public String getTxtJugador2() {
        return txtJugador2.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContinuar = new javax.swing.JButton();
        cbColor = new javax.swing.JComboBox<>();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        jlFondoPersonaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonContinuar.png"))); // NOI18N
        btnContinuar.setToolTipText("");
        btnContinuar.setActionCommand("Continuar");
        btnContinuar.setBorderPainted(false);
        btnContinuar.setContentAreaFilled(false);
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, -1, -1));

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Amarillo", "Rojo", "Azul", "Verde" }));
        getContentPane().add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        txtJugador1.setColumns(20);
        txtJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, 40));

        txtJugador2.setColumns(20);
        getContentPane().add(txtJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 422, -1, 50));

        jlFondoPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPersonaje.png"))); // NOI18N
        getContentPane().add(jlFondoPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JLabel jlFondoPersonaje;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
