/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.PrincipalController;

/**
 *
 * @author sebas
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(PrincipalController controlador) {
        initComponents();
        escuchar(controlador);
    }

    public void escuchar(PrincipalController controlador){
        
        btnJugar.addActionListener(controlador);
        btnInstrucciones.addActionListener(controlador);
        btnHistoriaJuego.addActionListener(controlador);
        btnCreditos.addActionListener(controlador);
        btnSalir.addActionListener(controlador);

    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnHistoriaJuego = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnSonido = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugarPrincipal.png"))); // NOI18N
        btnJugar.setActionCommand("Jugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instruccionesPrincipal.png"))); // NOI18N
        btnInstrucciones.setActionCommand("Instrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/creditosPrincipal.png"))); // NOI18N
        btnCreditos.setActionCommand("Creditos");
        btnCreditos.setBorderPainted(false);
        btnCreditos.setContentAreaFilled(false);
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        btnHistoriaJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historiaPrincipal.png"))); // NOI18N
        btnHistoriaJuego.setToolTipText("");
        btnHistoriaJuego.setActionCommand("HistoriaJuego");
        btnHistoriaJuego.setBorderPainted(false);
        btnHistoriaJuego.setContentAreaFilled(false);
        getContentPane().add(btnHistoriaJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonSalir.png"))); // NOI18N
        btnSalir.setActionCommand("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, -1, -1));

        btnSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sonido.png"))); // NOI18N
        btnSonido.setActionCommand("Sonido");
        btnSonido.setBorderPainted(false);
        btnSonido.setContentAreaFilled(false);
        getContentPane().add(btnSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPrincipal.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoriaJuego;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSonido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
