/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

/**
 *
 * @author sebas
 */
public class GUIWin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIWin.class.getName());

    /**
     * Creates new form GUIWin
     */
    public GUIWin() {
        initComponents();
    }
    
    
    public void setEstadisticas(String mensaje){
        jlEstadisticasFinal.setText(mensaje);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWinReiniciar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        jlEstadisticasFinal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWinReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonReiniciar.png"))); // NOI18N
        btnWinReiniciar.setActionCommand("ReiniciarWin");
        btnWinReiniciar.setBorderPainted(false);
        btnWinReiniciar.setContentAreaFilled(false);
        getContentPane().add(btnWinReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInicio.png"))); // NOI18N
        btnVolverMenu.setActionCommand("MenuWin");
        btnVolverMenu.setBorderPainted(false);
        btnVolverMenu.setContentAreaFilled(false);
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jlEstadisticasFinal.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlEstadisticasFinal.setText("0");
        getContentPane().add(jlEstadisticasFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelVictoria.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIWin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JButton btnWinReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlEstadisticasFinal;
    // End of variables declaration//GEN-END:variables
}
