/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.ControladorJuego;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author sebas
 */
public class PanelControl extends javax.swing.JPanel {

    GUIJugador guiJugador;
    
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
        this.guiJugador=guiJugador;
    }
    
    
    public void escuchar(ControladorJuego controlador){
        btnAtras.addActionListener(controlador);
        btnDado.addActionListener(controlador);
        btnDetener.addActionListener(controlador);
        btnIniciar.addActionListener(controlador);
        btnPausar.addActionListener(controlador);
    }
    
     public void setJlNombreJugador1(String jlNombreJugador1) {
        this.jlNombreJugador1.setText(jlNombreJugador1);
    }

    public void setJlNombreJugador2(String jlNombreJugador2) {
        this.jlNombreJugador2.setText(jlNombreJugador2);
    }

    public void setJlPuntosJuagdor2(int puntos) {
        jlPuntosJugador2.setText("Puntos: " + puntos);
    }

    public void setJlPuntosJugador1(int puntos) {
        jlPuntosJugador1.setText("Puntos: " + puntos);
    }
    
    public void resaltarTurno(int jugadorActivo) {
        jlNombreJugador1.setForeground(Color.BLACK);
        jlNombreJugador2.setForeground(Color.BLACK);
        
        jlPuntosJugador1.setForeground(Color.WHITE);
        jlPuntosJugador2.setForeground(Color.WHITE);
        
        
        if (jugadorActivo == 1){
            jlNombreJugador1.setForeground(Color.RED);
            jlPuntosJugador1.setForeground(Color.GREEN);
        } else if (jugadorActivo == 2){
            jlNombreJugador2.setForeground(Color.RED);
            jlPuntosJugador2.setForeground(Color.GREEN);
        
        }
    }
    
    public void setJLPuntosJugador1(int puntos){
        jlPuntosJugador1.setText("Puntos: " + puntos);
    }
    
    public void setJLPuntosJugador2(int puntos){
        jlPuntosJugador2.setText("Puntos: " + puntos);
    }
    
    public String getJlTime() {
        return jlTime.getText();
    }

    public void setJlTime(String jlTime) {
        this.jlTime.setText(jlTime);
    }

    
    public void setColor(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTime = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        btnDado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jlNombreJugador1 = new javax.swing.JLabel();
        jlNombreJugador2 = new javax.swing.JLabel();
        jlPuntosJugador1 = new javax.swing.JLabel();
        jlPuntosJugador2 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTime.setBackground(new java.awt.Color(235, 192, 96));
        jlTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTime.setOpaque(true);
        add(jlTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 130, 40));

        btnIniciar.setText("Iniciar");
        add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        btnPausar.setText("Pausar");
        add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        btnDetener.setText("Detener");
        add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado1.1.png"))); // NOI18N
        btnDado.setActionCommand("Dado");
        btnDado.setBorderPainted(false);
        btnDado.setContentAreaFilled(false);
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtras.setActionCommand("AtrasPanelControl");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        jlNombreJugador1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlNombreJugador1.setText("Jugador1");
        add(jlNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        jlNombreJugador2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlNombreJugador2.setText("Jugador2");
        add(jlNombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        jlPuntosJugador1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlPuntosJugador1.setForeground(new java.awt.Color(255, 255, 255));
        jlPuntosJugador1.setText("Puntos: 5");
        add(jlPuntosJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        jlPuntosJugador2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlPuntosJugador2.setForeground(new java.awt.Color(255, 255, 255));
        jlPuntosJugador2.setText("Puntos: 5");
        add(jlPuntosJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TableroFondo.png"))); // NOI18N
        add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlNombreJugador1;
    private javax.swing.JLabel jlNombreJugador2;
    private javax.swing.JLabel jlPuntosJugador1;
    private javax.swing.JLabel jlPuntosJugador2;
    private javax.swing.JLabel jlTime;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnDado(){
    
        return btnDado;
    
    }

}
