/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisc5k782.view;

import com.mycompany.parchisc5k782.controller.ControladorJuego;
import javax.swing.JLabel;

/**
 *
 * @author sebas
 */
public class PanelControl extends javax.swing.JPanel {

    GUIJugador guiJugador;
    
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
        this.guiJugador=guiJugador;
    }
    
    
    public void escuchar(ControladorJuego controlador){
        btnAtras.addActionListener(controlador);
        btnDado.addActionListener(controlador);
    
    }
    
     public void setJlNombreJugador1(String jlNombreJugador1) {
        this.jlNombreJugador1.setText(jlNombreJugador1);
    }

    public void setJlNombreJugador2(String jlNombreJugador2) {
        this.jlNombreJugador2.setText(jlNombreJugador2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jlNombreJugador1 = new javax.swing.JLabel();
        jlNombreJugador2 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDado.setText("Dado");
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtras.setActionCommand("AtrasPanelControl");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        jlNombreJugador1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlNombreJugador1.setText("Jugador1");
        add(jlNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        jlNombreJugador2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlNombreJugador2.setText("Jugador2");
        add(jlNombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TableroFondo.png"))); // NOI18N
        add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDado;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlNombreJugador1;
    private javax.swing.JLabel jlNombreJugador2;
    // End of variables declaration//GEN-END:variables
}
